update cve

diff --git a/jobs/postgres-9.4/templates/pre-start b/jobs/postgres-9.4/templates/pre-start
--- a/jobs/postgres-9.4/templates/pre-start
+++ b/jobs/postgres-9.4/templates/pre-start
@@ -7,6 +7,11 @@ if [[ -d /var/vcap/store/postgres-10 ]]; then
   exit 1
 fi
 
+if [[ -d /var/vcap/store/postgres-11 ]]; then
+  echo "Intentionally failing because data from a newer postgres job may already exist in /var/vcap/store/postgres-11"
+  exit 1
+fi
+
 if [[ -d /var/vcap/store/postgres ]]; then
   echo "Please use a previous bosh release version (264.x or lower) to migrate data from postgres to postgres-9.4."
   exit 1
